spring.application.name=storefront
spring.datasource.url=jdbc:h2:mem:storefrontdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
PAYMENT_API_KEY=sk_live_4xG9rP2vA1q7fL9kM3jN5bH8fake
server.port=5020
server.ssl.enabled=false
server.tomcat.basedir=./tmp